# Numpy

## Creating 1-D Array

In [ ]:
import numpy as np

#1-D Array
arr = np.array([2,4,6])

#2-D Array
arr2 = np.array([[1,3],[2,4]])

#3-D Array
arr3 = np.array([[[1,3,4],[3,4,5],[5,6,7,]]])


# print(arr)

# print(arr2)

# print(arr3)

[2 4 6]
[[1 3]
 [2 4]]
[[[1 3 4]
  [3 4 5]
  [5 6 7]]]


# Pandas

## installing Pandas

pip install pandas

In [10]:
import pandas as pd

employee = {
    'name' : ["shashi", "Joy", "Aman"],
    "Age" : [22,21,24],
    "City" : ["Ranchi", "Ranchi", "Rajasthan"],
    "Salary" : [72550, 89000, 200]
}

df = pd.DataFrame(employee)
print(df)


     name  Age       City  Salary
0  shashi   22     Ranchi   72550
1     Joy   21     Ranchi   89000
2    Aman   24  Rajasthan     200
